import { createWccClient, isSupabaseConfigured as hasSupabaseConfig } from '@/lib/wcc-client';
import type { Patient, WhatsAppOptInStatus } from '@/types';
export const WCC_CONTACTS_PAGE_SIZE = 20;
export type WccLinkedPatient = Pick<Patient,'id'|'fullName'|'phoneE164'>;
export type WccContactRow = { id:string; phoneE164:string; whatsappProfileName?:string; displayName?:string; linkedPatientId?:string; linkedPatient?:WccLinkedPatient; optInStatus:WhatsAppOptInStatus; firstSeenAt:string; lastSeenAt:string; lastMessageAt?:string; createdAt:string };
export type WccContactDetail = { isSupabaseConfigured:boolean; isConfiguredButUnavailable:boolean; contact?:WccContactRow; conversations:unknown[]; escalations:unknown[]; intents:unknown[] };
export type WccContactsList = { isSupabaseConfigured:boolean; isConfiguredButUnavailable:boolean; contacts:WccContactRow[]; page:number; pageSize:number; totalCount:number; totalPages:number };
type Row=Record<string,unknown>; type Result<T=Row>={data?:T[]|null;error?:{message?:string}|null;count?:number|null}; type Single<T=Row>={data?:T|null;error?:{message?:string}|null}; type Query=PromiseLike<Result>&{select:(...a:unknown[])=>Query;eq:(...a:unknown[])=>Query;in:(...a:unknown[])=>Query;order:(...a:unknown[])=>Query;range:(...a:unknown[])=>Query;maybeSingle:()=>Promise<Single>}; type Db={from:(t:string)=>Query};
const s=(v:unknown)=>typeof v==='string'&&v.length>0?v:undefined; const pageOf=(p:unknown)=>{const x=Number(p??1);return Number.isFinite(x)&&x>0?Math.floor(x):1}; async function db(){return await createWccClient() as unknown as Db} async function rows<T>(q:Query){const r=await q as Result<T>; if(r.error) throw new Error(r.error.message); return r} function empty(page=1,o:Partial<WccContactsList>={}):WccContactsList{return {isSupabaseConfigured:false,isConfiguredButUnavailable:false,contacts:[],page,pageSize:WCC_CONTACTS_PAGE_SIZE,totalCount:0,totalPages:0,...o}}
function mapContact(r:Row, patients=new Map<string,WccLinkedPatient>()):WccContactRow{const linkedPatientId=s(r.linked_patient_id); return {id:r.id as string,phoneE164:r.phone_e164 as string,whatsappProfileName:s(r.whatsapp_profile_name),displayName:s(r.display_name)??s(r.whatsapp_profile_name),linkedPatientId,linkedPatient:linkedPatientId?patients.get(linkedPatientId):undefined,optInStatus:r.opt_in_status as WhatsAppOptInStatus,firstSeenAt:r.first_seen_at as string,lastSeenAt:r.last_seen_at as string,lastMessageAt:s(r.last_message_at),createdAt:r.created_at as string}}
async function patientsFor(d:Db, ids:string[]){const u=[...new Set(ids.filter(Boolean))]; if(!u.length)return new Map<string,WccLinkedPatient>(); const r=await rows<Row>(d.from('patients').select('id, full_name, phone_e164').in('id',u).range(0,u.length-1)); return new Map((r.data??[]).map(x=>[x.id as string,{id:x.id as string,fullName:x.full_name as string,phoneE164:x.phone_e164 as string}]));}
export async function getWccContactsList(pageInput=1):Promise<WccContactsList>{const page=pageOf(pageInput); if(!hasSupabaseConfig())return empty(page); try{const d=await db(); const from=(page-1)*WCC_CONTACTS_PAGE_SIZE; const r=await rows<Row>(d.from('whatsapp_contacts').select('id, phone_e164, whatsapp_profile_name, display_name, linked_patient_id, opt_in_status, first_seen_at, last_seen_at, last_message_at, created_at',{count:'exact'}).order('last_message_at',{ascending:false}).range(from,from+WCC_CONTACTS_PAGE_SIZE-1)); const patients=await patientsFor(d,(r.data??[]).map(x=>s(x.linked_patient_id)).filter(Boolean) as string[]); const total=r.count??r.data?.length??0; return {isSupabaseConfigured:true,isConfiguredButUnavailable:false,contacts:(r.data??[]).map(x=>mapContact(x,patients)),page,pageSize:WCC_CONTACTS_PAGE_SIZE,totalCount:total,totalPages:Math.max(1,Math.ceil(total/WCC_CONTACTS_PAGE_SIZE))};}catch{return empty(page,{isSupabaseConfigured:true,isConfiguredButUnavailable:true})}}
export async function getWccContactDetail(contactId:string):Promise<WccContactDetail>{if(!hasSupabaseConfig())return {isSupabaseConfigured:false,isConfiguredButUnavailable:false,conversations:[],escalations:[],intents:[]}; try{const d=await db(); const c=await d.from('whatsapp_contacts').select('id, phone_e164, whatsapp_profile_name, display_name, linked_patient_id, opt_in_status, first_seen_at, last_seen_at, last_message_at, created_at').eq('id',contactId).maybeSingle(); if(c.error)throw new Error(c.error.message); const patients=await patientsFor(d,[s(c.data?.linked_patient_id)].filter(Boolean) as string[]); const [conversations,escalations,intents]=await Promise.all([rows(d.from('whatsapp_conversations').select('id, status, last_intent, last_message_at, last_inbound_at, last_outbound_at, booking_context').eq('contact_id',contactId).order('last_message_at',{ascending:false}).range(0,19)),rows(d.from('whatsapp_escalations').select('id, reason, priority, status, summary, opened_at, resolved_at').eq('contact_id',contactId).order('opened_at',{ascending:false}).range(0,19)),rows(d.from('whatsapp_intents').select('id, intent_type, confidence, summary, status, detected_at').eq('contact_id',contactId).order('detected_at',{ascending:false}).range(0,19))]); return {isSupabaseConfigured:true,isConfiguredButUnavailable:false,contact:c.data?mapContact(c.data,patients):undefined,conversations:conversations.data??[],escalations:escalations.data??[],intents:intents.data??[]};}catch{return {isSupabaseConfigured:true,isConfiguredButUnavailable:true,conversations:[],escalations:[],intents:[]}}}
