import { createWccClient, isSupabaseConfigured as hasSupabaseConfig } from '@/lib/wcc-client';
import type { WhatsAppConversationStatus, WhatsAppEscalationPriority, WhatsAppEscalationStatus } from '@/types';
export const WCC_ESCALATIONS_PAGE_SIZE = 20;
export const wccEscalationStatuses: WhatsAppEscalationStatus[] = ['open','acknowledged','resolved','canceled'];
export const wccEscalationPriorities: WhatsAppEscalationPriority[] = ['urgent','high','normal','low'];
export type WccEscalationContact={id:string;phoneE164:string;whatsappProfileName?:string;displayName?:string;linkedPatientId?:string};
export type WccEscalationConversation={id:string;status:WhatsAppConversationStatus;lastIntent?:string;lastMessageAt?:string;bookingContext?:unknown};
export type WccEscalationRow={id:string;conversationId:string;contactId:string;messageId?:string;intentId?:string;reason:string;priority:WhatsAppEscalationPriority;status:WhatsAppEscalationStatus;summary?:string;assignedTo?:string;openedAt:string;resolvedAt?:string;createdAt:string;updatedAt:string;contact?:WccEscalationContact;conversation?:WccEscalationConversation};
export type WccEscalationsFilters={page?:number|string;status?:string;priority?:string};
export type WccEscalationsQueue={isSupabaseConfigured:boolean;isConfiguredButUnavailable:boolean;escalations:WccEscalationRow[];page:number;pageSize:number;totalCount:number;totalPages:number;status?:WhatsAppEscalationStatus;priority?:WhatsAppEscalationPriority};
type Row=Record<string,unknown>; type Result<T=Row>={data?:T[]|null;error?:{message?:string}|null;count?:number|null}; type Query=PromiseLike<Result>&{select:(...a:unknown[])=>Query;eq:(...a:unknown[])=>Query;in:(...a:unknown[])=>Query;order:(...a:unknown[])=>Query;range:(...a:unknown[])=>Query}; type Db={from:(t:string)=>Query};
const s=(v:unknown)=>typeof v==='string'&&v.length>0?v:undefined; const pageOf=(p:unknown)=>{const x=Number(p??1);return Number.isFinite(x)&&x>0?Math.floor(x):1}; const statusOf=(v:unknown)=>wccEscalationStatuses.includes(v as WhatsAppEscalationStatus)?v as WhatsAppEscalationStatus:undefined; const priorityOf=(v:unknown)=>wccEscalationPriorities.includes(v as WhatsAppEscalationPriority)?v as WhatsAppEscalationPriority:undefined; async function db(){return await createWccClient() as unknown as Db} async function rows<T>(q:Query){const r=await q as Result<T>; if(r.error) throw new Error(r.error.message); return r} function empty(f:WccEscalationsFilters={},o:Partial<WccEscalationsQueue>={}):WccEscalationsQueue{const page=pageOf(f.page); return {isSupabaseConfigured:false,isConfiguredButUnavailable:false,escalations:[],page,pageSize:WCC_ESCALATIONS_PAGE_SIZE,totalCount:0,totalPages:0,status:statusOf(f.status),priority:priorityOf(f.priority),...o}}
function mapContact(r:Row):WccEscalationContact{return {id:r.id as string,phoneE164:r.phone_e164 as string,whatsappProfileName:s(r.whatsapp_profile_name),displayName:s(r.display_name)??s(r.whatsapp_profile_name),linkedPatientId:s(r.linked_patient_id)}}
function mapConversation(r:Row):WccEscalationConversation{return {id:r.id as string,status:r.status as WhatsAppConversationStatus,lastIntent:s(r.last_intent),lastMessageAt:s(r.last_message_at),bookingContext:r.booking_context}}
function mapEsc(r:Row, contacts=new Map<string,WccEscalationContact>(), convs=new Map<string,WccEscalationConversation>()):WccEscalationRow{return {id:r.id as string,conversationId:r.conversation_id as string,contactId:r.contact_id as string,messageId:s(r.message_id),intentId:s(r.intent_id),reason:r.reason as string,priority:r.priority as WhatsAppEscalationPriority,status:r.status as WhatsAppEscalationStatus,summary:s(r.summary),assignedTo:s(r.assigned_to),openedAt:r.opened_at as string,resolvedAt:s(r.resolved_at),createdAt:r.created_at as string,updatedAt:r.updated_at as string,contact:contacts.get(r.contact_id as string),conversation:convs.get(r.conversation_id as string)}}
async function contactsFor(d:Db,ids:string[]){if(!ids.length)return new Map<string,WccEscalationContact>(); const r=await rows<Row>(d.from('whatsapp_contacts').select('id, phone_e164, whatsapp_profile_name, display_name, linked_patient_id').in('id',ids).range(0,ids.length-1)); return new Map((r.data??[]).map(x=>[x.id as string,mapContact(x)]));} async function convsFor(d:Db,ids:string[]){if(!ids.length)return new Map<string,WccEscalationConversation>(); const r=await rows<Row>(d.from('whatsapp_conversations').select('id, status, last_intent, last_message_at, booking_context').in('id',ids).range(0,ids.length-1)); return new Map((r.data??[]).map(x=>[x.id as string,mapConversation(x)]));}
export async function getWccEscalationsQueue(filters:WccEscalationsFilters={}):Promise<WccEscalationsQueue>{const page=pageOf(filters.page); const status=statusOf(filters.status); const priority=priorityOf(filters.priority); if(!hasSupabaseConfig())return empty(filters); try{const d=await db(); const from=(page-1)*WCC_ESCALATIONS_PAGE_SIZE; let q=d.from('whatsapp_escalations').select('id, conversation_id, contact_id, message_id, intent_id, reason, priority, status, summary, assigned_to, opened_at, resolved_at, created_at, updated_at',{count:'exact'}); if(status) q=q.eq('status',status); if(priority) q=q.eq('priority',priority); const r=await rows<Row>(q.order('opened_at',{ascending:false}).range(from,from+WCC_ESCALATIONS_PAGE_SIZE-1)); const [contacts,convs]=await Promise.all([contactsFor(d,(r.data??[]).map(x=>x.contact_id as string)),convsFor(d,(r.data??[]).map(x=>x.conversation_id as string))]); const total=r.count??r.data?.length??0; return {isSupabaseConfigured:true,isConfiguredButUnavailable:false,escalations:(r.data??[]).map(x=>mapEsc(x,contacts,convs)),page,pageSize:WCC_ESCALATIONS_PAGE_SIZE,totalCount:total,totalPages:Math.max(1,Math.ceil(total/WCC_ESCALATIONS_PAGE_SIZE)),status,priority};}catch{return empty(filters,{isSupabaseConfigured:true,isConfiguredButUnavailable:true})}}
