import { createWccClient, isSupabaseConfigured as hasSupabaseConfig } from '@/lib/wcc-client';
import type { WhatsAppConversationStatus, WhatsAppIntentStatus, WhatsAppIntentType, WhatsAppMessageDirection, WhatsAppMessageStatus } from '@/types';
export const WCC_CONVERSATIONS_PAGE_SIZE = 20;
export type WccConversationContact = { id: string; phoneE164: string; whatsappProfileName?: string; displayName?: string; linkedPatientId?: string };
export type WccConversationMessage = { id: string; conversationId: string; contactId: string; whatsappMessageId: string; direction: WhatsAppMessageDirection; messageType: string; body?: string; status: WhatsAppMessageStatus; occurredAt: string; processedAt?: string; createdAt: string };
export type WccConversationIntent = { id: string; conversationId: string; messageId: string; contactId: string; intentType: WhatsAppIntentType; confidence?: number; summary?: string; status: WhatsAppIntentStatus; detectedAt: string };
export type WccConversationRow = { id: string; contactId: string; bookingContext?: unknown; status: WhatsAppConversationStatus; lastIntent?: string; lastMessageAt?: string; lastInboundAt?: string; lastOutboundAt?: string; closedAt?: string; createdAt: string; updatedAt: string; contact?: WccConversationContact; latestInbound?: WccConversationMessage; latestOutbound?: WccConversationMessage; latestIntent?: WccConversationIntent };
export type WccConversationsList = { isSupabaseConfigured: boolean; isConfiguredButUnavailable: boolean; conversations: WccConversationRow[]; page: number; pageSize: number; totalCount: number; totalPages: number };
export type WccConversationDetail = { isSupabaseConfigured: boolean; isConfiguredButUnavailable: boolean; conversation?: WccConversationRow; messages: WccConversationMessage[]; intents: WccConversationIntent[] };
export type WccConversationsFilters = { page?: number | string };
type Row = Record<string, unknown>; type Result<T=Row>={data?:T[]|null;error?:{message?:string}|null;count?:number|null}; type Single<T=Row>={data?:T|null;error?:{message?:string}|null}; type Query=PromiseLike<Result>&{select:(...a:unknown[])=>Query;eq:(...a:unknown[])=>Query;in:(...a:unknown[])=>Query;order:(...a:unknown[])=>Query;range:(...a:unknown[])=>Query;maybeSingle:()=>Promise<Single>}; type Db={from:(t:string)=>Query};
const s=(v:unknown)=>typeof v==='string'&&v.length>0?v:undefined; const n=(v:unknown)=>typeof v==='number'?v:(typeof v==='string'?Number(v):undefined); const pageOf=(p:unknown)=>{const x=Number(p??1);return Number.isFinite(x)&&x>0?Math.floor(x):1};
function mapContact(r:Row):WccConversationContact{return {id:r.id as string,phoneE164:r.phone_e164 as string,whatsappProfileName:s(r.whatsapp_profile_name),displayName:s(r.display_name)??s(r.whatsapp_profile_name),linkedPatientId:s(r.linked_patient_id)}}
function mapMessage(r:Row):WccConversationMessage{return {id:r.id as string,conversationId:r.conversation_id as string,contactId:r.contact_id as string,whatsappMessageId:r.whatsapp_message_id as string,direction:r.direction as WhatsAppMessageDirection,messageType:r.message_type as string,body:s(r.body),status:r.status as WhatsAppMessageStatus,occurredAt:r.occurred_at as string,processedAt:s(r.processed_at),createdAt:r.created_at as string}}
function mapIntent(r:Row):WccConversationIntent{return {id:r.id as string,conversationId:r.conversation_id as string,messageId:r.message_id as string,contactId:r.contact_id as string,intentType:r.intent_type as WhatsAppIntentType,confidence:n(r.confidence),summary:s(r.summary),status:r.status as WhatsAppIntentStatus,detectedAt:r.detected_at as string}}
function mapConv(r:Row, contacts=new Map<string,WccConversationContact>()):WccConversationRow{return {id:r.id as string,contactId:r.contact_id as string,bookingContext:r.booking_context,status:r.status as WhatsAppConversationStatus,lastIntent:s(r.last_intent),lastMessageAt:s(r.last_message_at),lastInboundAt:s(r.last_inbound_at),lastOutboundAt:s(r.last_outbound_at),closedAt:s(r.closed_at),createdAt:r.created_at as string,updatedAt:r.updated_at as string,contact:contacts.get(r.contact_id as string)}}
async function db(){return await createWccClient() as unknown as Db} async function rows<T>(q:Query){const r=await q as Result<T>; if(r.error) throw new Error(r.error.message); return r} function empty(page=1,o:Partial<WccConversationsList>={}):WccConversationsList{return {isSupabaseConfigured:false,isConfiguredButUnavailable:false,conversations:[],page,pageSize:WCC_CONVERSATIONS_PAGE_SIZE,totalCount:0,totalPages:0,...o}}
async function contactsFor(d:Db, ids:string[]){if(!ids.length)return new Map<string,WccConversationContact>(); const r=await rows<Row>(d.from('whatsapp_contacts').select('id, phone_e164, whatsapp_profile_name, display_name, linked_patient_id').in('id',ids).range(0,ids.length-1)); return new Map((r.data??[]).map(x=>[x.id as string,mapContact(x)]));}
export async function getWccConversationsList(filters:WccConversationsFilters={}):Promise<WccConversationsList>{const page=pageOf(filters.page); if(!hasSupabaseConfig())return empty(page); try{const d=await db(); const from=(page-1)*WCC_CONVERSATIONS_PAGE_SIZE; const r=await rows<Row>(d.from('whatsapp_conversations').select('id, contact_id, booking_context, status, last_intent, last_message_at, last_inbound_at, last_outbound_at, closed_at, created_at, updated_at',{count:'exact'}).order('last_message_at',{ascending:false}).range(from,from+WCC_CONVERSATIONS_PAGE_SIZE-1)); const contacts=await contactsFor(d,(r.data??[]).map(x=>x.contact_id as string)); const total=r.count??r.data?.length??0; return {isSupabaseConfigured:true,isConfiguredButUnavailable:false,conversations:(r.data??[]).map(x=>mapConv(x,contacts)),page,pageSize:WCC_CONVERSATIONS_PAGE_SIZE,totalCount:total,totalPages:Math.max(1,Math.ceil(total/WCC_CONVERSATIONS_PAGE_SIZE))};}catch{return empty(page,{isSupabaseConfigured:true,isConfiguredButUnavailable:true})}}
export async function getWccConversationDetail(conversationId:string):Promise<WccConversationDetail>{if(!hasSupabaseConfig())return {isSupabaseConfigured:false,isConfiguredButUnavailable:false,messages:[],intents:[]}; try{const d=await db(); const c=await d.from('whatsapp_conversations').select('id, contact_id, booking_context, status, last_intent, last_message_at, last_inbound_at, last_outbound_at, closed_at, created_at, updated_at').eq('id',conversationId).maybeSingle(); if(c.error)throw new Error(c.error.message); if(!c.data)return {isSupabaseConfigured:true,isConfiguredButUnavailable:false,messages:[],intents:[]}; const [contacts,messages,intents]=await Promise.all([contactsFor(d,[c.data.contact_id as string]),rows<Row>(d.from('whatsapp_messages').select('id, conversation_id, contact_id, whatsapp_message_id, direction, message_type, body, status, occurred_at, processed_at, created_at').eq('conversation_id',conversationId).order('occurred_at',{ascending:true}).range(0,49)),rows<Row>(d.from('whatsapp_intents').select('id, conversation_id, message_id, contact_id, intent_type, confidence, summary, status, detected_at').eq('conversation_id',conversationId).order('detected_at',{ascending:true}).range(0,49))]); return {isSupabaseConfigured:true,isConfiguredButUnavailable:false,conversation:mapConv(c.data,contacts),messages:(messages.data??[]).map(mapMessage),intents:(intents.data??[]).map(mapIntent)};}catch{return {isSupabaseConfigured:true,isConfiguredButUnavailable:true,messages:[],intents:[]}}}
