import { createWccClient, isSupabaseConfigured as hasSupabaseConfig } from '@/lib/wcc-client';
import type { WhatsAppKnowledgeEntry, WhatsAppKnowledgeStatus } from '@/types';

export const WCC_KNOWLEDGE_PAGE_SIZE = 20;
export const wccKnowledgeStatuses: WhatsAppKnowledgeStatus[] = ['draft', 'approved', 'archived'];
export type WccKnowledgeListFilters = { page?: number | string; status?: string };
export type WccKnowledgeList = { isSupabaseConfigured: boolean; isConfiguredButUnavailable: boolean; entries: WhatsAppKnowledgeEntry[]; page: number; pageSize: number; totalCount: number; totalPages: number; status?: WhatsAppKnowledgeStatus };
export type WccKnowledgeDetail = { isSupabaseConfigured: boolean; isConfiguredButUnavailable: boolean; entry?: WhatsAppKnowledgeEntry };
export type WccKnowledgeMutationResult = { ok: boolean; message: string; entryId?: string; errors?: Partial<Record<'id' | 'topic' | 'question' | 'answer' | 'tags' | 'source' | 'status', string>> };
export type WccKnowledgeInput = { topic: unknown; question: unknown; answer: unknown; tags?: unknown; source?: unknown; status: unknown };

type Row = Record<string, unknown>;
type Result<T = Row> = { data?: T[] | null; error?: { message?: string } | null; count?: number | null };
type Single<T = Row> = { data?: T | null; error?: { message?: string } | null };
type Query = PromiseLike<Result> & { select: (...args: unknown[]) => Query; eq: (...args: unknown[]) => Query; order: (...args: unknown[]) => Query; range: (...args: unknown[]) => Query; insert: (...args: unknown[]) => Query; update: (...args: unknown[]) => Query; maybeSingle: () => Promise<Single>; single: () => Promise<Single> };
type Db = { from: (table: string) => Query };

export class WccKnowledgeValidationError extends Error { constructor(public errors: NonNullable<WccKnowledgeMutationResult['errors']>) { super('Knowledge entry validation failed'); this.name = 'WccKnowledgeValidationError'; } }
function normalizePage(page: unknown) { const n = Number(page ?? 1); return Number.isFinite(n) && n > 0 ? Math.floor(n) : 1; }
export function normalizeWccKnowledgeStatus(status: unknown): WhatsAppKnowledgeStatus | undefined { return wccKnowledgeStatuses.includes(status as WhatsAppKnowledgeStatus) ? status as WhatsAppKnowledgeStatus : undefined; }
function emptyList(filters: WccKnowledgeListFilters = {}, o: Partial<WccKnowledgeList> = {}): WccKnowledgeList { const page = normalizePage(filters.page); return { isSupabaseConfigured: false, isConfiguredButUnavailable: false, entries: [], page, pageSize: WCC_KNOWLEDGE_PAGE_SIZE, totalCount: 0, totalPages: 0, status: normalizeWccKnowledgeStatus(filters.status), ...o }; }
function mapEntry(r: Row): WhatsAppKnowledgeEntry { return { id: r.id as string, topic: r.topic as string, question: r.question as string, answer: r.answer as string, tags: Array.isArray(r.tags) ? r.tags.filter((t): t is string => typeof t === 'string') : [], source: typeof r.source === 'string' ? r.source : null, status: r.status as WhatsAppKnowledgeStatus, approvedAt: (r.approved_at as string | null) ?? null, createdAt: r.created_at as string, updatedAt: r.updated_at as string }; }
function readString(v: unknown) { return typeof v === 'string' ? v.trim() : ''; }
function normalizeTags(v: unknown) { const raw = Array.isArray(v) ? v.join(',') : readString(v); return raw.split(',').map((t) => t.trim()).filter(Boolean); }
export function validateWccKnowledgeInput(input: WccKnowledgeInput) { const topic = readString(input.topic), question = readString(input.question), answer = readString(input.answer), source = readString(input.source), status = normalizeWccKnowledgeStatus(input.status); const errors: NonNullable<WccKnowledgeMutationResult['errors']> = {}; if (!topic) errors.topic = 'El tema es obligatorio.'; if (!question) errors.question = 'La pregunta es obligatoria.'; if (!answer) errors.answer = 'La respuesta es obligatoria.'; if (!status) errors.status = 'El estado no es válido.'; if (Object.keys(errors).length) throw new WccKnowledgeValidationError(errors); return { topic, question, answer, tags: normalizeTags(input.tags), source: source || null, status: status! }; }
async function db() { return await createWccClient() as unknown as Db; }
export async function getWccKnowledgeList(filters: WccKnowledgeListFilters = {}): Promise<WccKnowledgeList> { const page = normalizePage(filters.page); const status = normalizeWccKnowledgeStatus(filters.status); if (!hasSupabaseConfig()) return emptyList(filters); try { const d = await db(); const from = (page - 1) * WCC_KNOWLEDGE_PAGE_SIZE; let q = d.from('whatsapp_knowledge_entries').select('id, topic, question, answer, tags, source, status, approved_at, created_at, updated_at', { count: 'exact' }); if (status) q = q.eq('status', status); const r = await q.order('updated_at', { ascending: false }).range(from, from + WCC_KNOWLEDGE_PAGE_SIZE - 1) as Result; if (r.error) throw new Error(r.error.message); const total = r.count ?? r.data?.length ?? 0; return { isSupabaseConfigured: true, isConfiguredButUnavailable: false, entries: (r.data ?? []).map(mapEntry), page, pageSize: WCC_KNOWLEDGE_PAGE_SIZE, totalCount: total, totalPages: Math.max(1, Math.ceil(total / WCC_KNOWLEDGE_PAGE_SIZE)), status }; } catch { return emptyList(filters, { isSupabaseConfigured: true, isConfiguredButUnavailable: true }); } }
export async function getWccKnowledgeEntry(entryId: string): Promise<WccKnowledgeDetail> { if (!hasSupabaseConfig()) return { isSupabaseConfigured: false, isConfiguredButUnavailable: false }; try { const r = await (await db()).from('whatsapp_knowledge_entries').select('id, topic, question, answer, tags, source, status, approved_at, created_at, updated_at').eq('id', entryId).maybeSingle(); if (r.error) throw new Error(r.error.message); return { isSupabaseConfigured: true, isConfiguredButUnavailable: false, entry: r.data ? mapEntry(r.data) : undefined }; } catch { return { isSupabaseConfigured: true, isConfiguredButUnavailable: true }; } }
function unavailable(): WccKnowledgeMutationResult { return { ok: false, message: 'Supabase no está configurado.' }; }
export async function createWccKnowledgeEntry(input: WccKnowledgeInput): Promise<WccKnowledgeMutationResult> { if (!hasSupabaseConfig()) return unavailable(); try { const payload = validateWccKnowledgeInput(input); const r = await (await db()).from('whatsapp_knowledge_entries').insert({ ...payload, approved_at: payload.status === 'approved' ? new Date().toISOString() : null }).select('id').single(); if (r.error) throw new Error(r.error.message); return { ok: true, message: 'Entrada creada.', entryId: r.data?.id as string }; } catch (e) { if (e instanceof WccKnowledgeValidationError) return { ok: false, message: 'Revisa los campos.', errors: e.errors }; return { ok: false, message: 'No se pudo guardar la entrada.' }; } }
export async function updateWccKnowledgeEntry(entryId: string, input: WccKnowledgeInput): Promise<WccKnowledgeMutationResult> { if (!hasSupabaseConfig()) return unavailable(); try { const payload = validateWccKnowledgeInput(input); const r = await (await db()).from('whatsapp_knowledge_entries').update({ ...payload, approved_at: payload.status === 'approved' ? new Date().toISOString() : null }).eq('id', entryId).select('id').single(); if (r.error) throw new Error(r.error.message); return { ok: true, message: 'Entrada actualizada.', entryId: r.data?.id as string }; } catch (e) { if (e instanceof WccKnowledgeValidationError) return { ok: false, message: 'Revisa los campos.', errors: e.errors }; return { ok: false, message: 'No se pudo actualizar la entrada.' }; } }
export async function updateWccKnowledgeStatus(entryId: string, statusInput: unknown): Promise<WccKnowledgeMutationResult> { const status = normalizeWccKnowledgeStatus(statusInput); if (!status) return { ok: false, message: 'Estado inválido.' }; if (!hasSupabaseConfig()) return unavailable(); try { const r = await (await db()).from('whatsapp_knowledge_entries').update({ status, approved_at: status === 'approved' ? new Date().toISOString() : null }).eq('id', entryId).select('id').single(); if (r.error) throw new Error(r.error.message); return { ok: true, message: 'Estado actualizado.', entryId: r.data?.id as string }; } catch { return { ok: false, message: 'No se pudo actualizar el estado.' }; } }
